# Generated by Django 4.0.5 on 2023-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(choices=[['Fiat', 'Fiat'], ['Chevrolet', 'Chevrolet'], ['Ford', 'Ford'], ['Toyota', 'Toyota']], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
