# Generated by Django 4.0.5 on 2023-07-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculos_marca_alter_vehiculos_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculos',
            old_name='Precio',
            new_name='precio',
        ),
    ]
