# Generated by Django 4.0.5 on 2023-07-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_alter_vehiculos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculos',
            options={},
        ),
    ]
