# Generated by Django 4.0.5 on 2023-07-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_alter_vehiculos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'permissions': [('visualizar_catalogo', 'Puede Visualizar catalogo Vehiculos'), ('add_vehiculomodel', 'Puede Agregar Vehiculo')]},
        ),
    ]
